[package]
name = "tesseract-rs"
version = "0.1.0"
edition = "2021"
authors = ["Cafer Can Gündoğdu <cafercangundogdu@gmail.com>"]
description = "Rust bindings for Tesseract OCR with built-in compilation"
license = "MIT"
repository = "https://github.com/cafercangundogdu/tesseract-rs"
documentation = "https://docs.rs/tesseract-rs"
readme = "README.md"
keywords = ["tesseract", "ocr", "bindings", "computer-vision", "text-recognition"]
categories = ["external-ffi-bindings", "computer-vision", "text-processing"]
build = "build.rs"
links = "tesseract"
rust-version = "1.65"

[dependencies]
libc = "0.2.159"
thiserror = "1.0.64"

[dev-dependencies]
image = "0.25.2"
imageproc = "0.25.0"

[build-dependencies]
cc = "1.1.30"
glob = "0.3.1"
cmake = "0.1.51"
reqwest = { version = "0.12.8", features = ["blocking"] }

[package.metadata.docs.rs]
features = ["docs-only"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
docs-only = []